### ISSUE TITLE
Update wiki "Installation via Github Release"

### ISSUE THREAD

**Issue by vevilo** [MWATelescope/mwalib#37]
Some of the commands need updated to be able to install v0.10.0 release (not sure about earlier releases).

Here are the updated lines:
Download release from mwalib github releases. (Where X.Y.Z is the current release version)
`wget "https://github.com/MWATelescope/mwalib/releases/download/vX.Y.Z/mwalib-vX.Y.Z-linux_x86_64.tar.gz" -O mwalib.tar.gz`

Install
`sudo cp mwalib/libmwalib.* /usr/local/lib`
`sudo cp mwalib/mwalib.h /usr/local/include`

**Comment by gsleap** [comment]
Thanks @vevilo for the update! I've made the changes to the wiki now.
