### ISSUE TITLE
Provide mechanism to read and interpret MWA flag file format (.mwaf)

### ISSUE THREAD

**Issue by gsleap** [MWATelescope/mwalib#9]
Need to check in cotter, what order the tiles/baselines are in.

**Comment by gsleap** [comment]
@cjordan @derwentx is this something mwalib should be doing, so hyperdrive and birli use common code to do this?

**Comment by cjordan** [comment]
Possibly. It may be easiest to just put that into Birli. One argument against that is if non-Rust users want code to interface with the mwafs, but that may be possible through Birli too.

**Comment by gsleap** [comment]
Closing as per @derwentx comment!
